### PR TITLE
Make python deps ~= instead of ==

### PR DESCRIPTION
**Pull request by zhenlu**

### CODE REVIEW

**Comment by zhenlu** [comment]
* **#63** <a href="https://app.graphite.dev/github/pr/lightsparkdev/lightspark-crypto-uniffi/63?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @zhenlu and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by jklein24 — COMMENTED** [review]
Will this also include minor and patch updates, though? Hackerone flagged elsewhere that we might want to pin to only patch updates in security-critical areas. I think for these, minor seems reasonable, though.

**Comment by zhenlu** [comment]
Yes these will include the miner updates.

**Comment by jklein24** [comment]
> Yes these will include the miner updates.

Not major though, right?

**Comment by zhenlu** [comment]
>= includes major, ~= doesn't. Which behavior do we want?

**Comment by jklein24** [comment]
> `>=` includes major, `~=` doesn't. Which behavior do we want?

Let's not include major - `~=`

**Comment by zhenlu** [comment]
updated

**Review by jklein24 — APPROVED** [review]

**Comment by zhenlu** [comment]
### Merge activity

* **May 20, 6:42 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/lightsparkdev/lightspark-crypto-uniffi/63) rebased this pull request as part of a merge.

**Pull request merged**
